### ISSUE TITLE
Incompatible declarations of getRecords function

### ISSUE THREAD

**Issue by NecroMan** [wintercms/wn-docs-plugin#22]
Last version of plugin (1.0.0-1.0.2) breaks `docs:process` command.

```
In MarkdownPageIndex.php line 46:
                                                                                               
  Declaration of Winter\Docs\Classes\MarkdownPageIndex::getRecords() must be compatible with   
  Winter\Docs\Classes\BasePageIndex::getRecords(): array                                       
```                                                                                               

Adding `: array` to `MarkdownPageIndex::getRecords` don't work because 

```
 Generator return type must be a supertype of Generator, array given 
```

Removing return type from `BasePageIndex::getRecords` or changing both to `iterable` skips this declarations checks but then command fails in 

```
In ArraySource.php line 133:
                                                
  Cannot use object of type Generator as array  
```                                             

Commit `dabad05` still works correctly.

Winter CMS 1.2.6, PHP 8.3.

**Comment by bennothommo** [comment]
Hi @NecroMan,

We had to change `ArraySource` to have no return type to allow it to return generators or arrays, as in our case, we were using the Docs plugin for our [Winter Docs](https://wintercms.com/docs) and were hitting out-of-memory issues. This plugin was changed to suit this, but the ArraySource changes are waiting for Winter CMS 1.2.7 to be released, which should be very soon.

In the meantime, if you're using Composer, you can require the Docs plugin at that specific commit that works if you want to roll it back to the working version:

```json
"require": {
    "winter/wn-docs-plugin": "dev-main#dabad05c1cfe306c962214f3d88167108cfe6dad"
}
```

That would tide your install over until Winter 1.2.7 is out.

**Comment by NecroMan** [comment]
Ok. I have already fixed commit for myself. Maybe it's worth fixing the Winter CMS version in composer.json so that others don't have similar problems?
Thanks!

**Comment by LukeTowers** [comment]
Winter 1.2.7 should be out tomorrow (today?) hopefully.
