### ISSUE TITLE
Search should search through contents, not just TOC

### ISSUE THREAD

**Issue by der-On** [wintercms/wn-docs-plugin#6]
As a user I want to be able to search the docs.

## Current behaviour

- I enter a search term into the search box
- the TOC gets filtered by the search term

## Expected behaviour

- I enter a search term into the search box
- I get a list of search results either below the search box (autocomplete) or in the main content area

**Comment by bennothommo** [comment]
This is now possible with the capabilities of the [Search plugin](https://github.com/wintercms/wn-search-plugin). This Docs plugin fully supports and integrates with that plugin.
